globalThis.atob = (s) => Buffer.from(s, "base64").toString("binary");
globalThis.btoa = (s) => Buffer.from(s, "binary").toString("base64");
globalThis.window = { atob: globalThis.atob, btoa: globalThis.btoa };
globalThis.document = { createElement: () => ({ getContext: () => null, style: {}, setAttribute() {}, appendChild() {}, click() {} }), body: { appendChild() {} } };
globalThis.navigator = { userAgent: "node" };
globalThis.URL = globalThis.URL ?? class { static createObjectURL() { return "blob:x"; } static revokeObjectURL() {} };
globalThis.Blob = globalThis.Blob ?? class { constructor(p){ this.p=p; } };
const m1 = await import("jspdf");
const m2 = await import("/dev-server/node_modules/jspdf/dist/jspdf.es.min.js").catch(()=>null);
console.log("same?", m1.jsPDF === m2?.jsPDF, !!m2);
const doc = new m1.jsPDF();
console.log("save type:", typeof doc.save);
doc.save = function(name) { console.log("INSTANCE SAVE", name); };
doc.text("hi", 50, 50);
doc.save("test.pdf");
