/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as HubStrategyRouteImport } from './routes/hub.strategy'
import { Route as HubStateRouteImport } from './routes/hub.state'
import { Route as HubMindRouteImport } from './routes/hub.mind'
import { Route as HubMentorRouteImport } from './routes/hub.mentor'
import { Route as HubJournalRouteImport } from './routes/hub.journal'
import { Route as HubChartRouteImport } from './routes/hub.chart'
import { Route as DevResetRouteImport } from './routes/dev.reset'
import { Route as HubJournalHistoryRouteImport } from './routes/hub.journal.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubStrategyRoute = HubStrategyRouteImport.update({
  id: '/hub/strategy',
  path: '/hub/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const HubStateRoute = HubStateRouteImport.update({
  id: '/hub/state',
  path: '/hub/state',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMindRoute = HubMindRouteImport.update({
  id: '/hub/mind',
  path: '/hub/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMentorRoute = HubMentorRouteImport.update({
  id: '/hub/mentor',
  path: '/hub/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const HubJournalRoute = HubJournalRouteImport.update({
  id: '/hub/journal',
  path: '/hub/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HubChartRoute = HubChartRouteImport.update({
  id: '/hub/chart',
  path: '/hub/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DevResetRoute = DevResetRouteImport.update({
  id: '/dev/reset',
  path: '/dev/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const HubJournalHistoryRoute = HubJournalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HubJournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/reset': typeof DevResetRoute
  '/hub/chart': typeof HubChartRoute
  '/hub/journal': typeof HubJournalRouteWithChildren
  '/hub/mentor': typeof HubMentorRoute
  '/hub/mind': typeof HubMindRoute
  '/hub/state': typeof HubStateRoute
  '/hub/strategy': typeof HubStrategyRoute
  '/hub/': typeof HubIndexRoute
  '/hub/journal/history': typeof HubJournalHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/reset': typeof DevResetRoute
  '/hub/chart': typeof HubChartRoute
  '/hub/journal': typeof HubJournalRouteWithChildren
  '/hub/mentor': typeof HubMentorRoute
  '/hub/mind': typeof HubMindRoute
  '/hub/state': typeof HubStateRoute
  '/hub/strategy': typeof HubStrategyRoute
  '/hub': typeof HubIndexRoute
  '/hub/journal/history': typeof HubJournalHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/reset': typeof DevResetRoute
  '/hub/chart': typeof HubChartRoute
  '/hub/journal': typeof HubJournalRouteWithChildren
  '/hub/mentor': typeof HubMentorRoute
  '/hub/mind': typeof HubMindRoute
  '/hub/state': typeof HubStateRoute
  '/hub/strategy': typeof HubStrategyRoute
  '/hub/': typeof HubIndexRoute
  '/hub/journal/history': typeof HubJournalHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev/reset'
    | '/hub/chart'
    | '/hub/journal'
    | '/hub/mentor'
    | '/hub/mind'
    | '/hub/state'
    | '/hub/strategy'
    | '/hub/'
    | '/hub/journal/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev/reset'
    | '/hub/chart'
    | '/hub/journal'
    | '/hub/mentor'
    | '/hub/mind'
    | '/hub/state'
    | '/hub/strategy'
    | '/hub'
    | '/hub/journal/history'
  id:
    | '__root__'
    | '/'
    | '/dev/reset'
    | '/hub/chart'
    | '/hub/journal'
    | '/hub/mentor'
    | '/hub/mind'
    | '/hub/state'
    | '/hub/strategy'
    | '/hub/'
    | '/hub/journal/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevResetRoute: typeof DevResetRoute
  HubChartRoute: typeof HubChartRoute
  HubJournalRoute: typeof HubJournalRouteWithChildren
  HubMentorRoute: typeof HubMentorRoute
  HubMindRoute: typeof HubMindRoute
  HubStateRoute: typeof HubStateRoute
  HubStrategyRoute: typeof HubStrategyRoute
  HubIndexRoute: typeof HubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/strategy': {
      id: '/hub/strategy'
      path: '/hub/strategy'
      fullPath: '/hub/strategy'
      preLoaderRoute: typeof HubStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/state': {
      id: '/hub/state'
      path: '/hub/state'
      fullPath: '/hub/state'
      preLoaderRoute: typeof HubStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/mind': {
      id: '/hub/mind'
      path: '/hub/mind'
      fullPath: '/hub/mind'
      preLoaderRoute: typeof HubMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/mentor': {
      id: '/hub/mentor'
      path: '/hub/mentor'
      fullPath: '/hub/mentor'
      preLoaderRoute: typeof HubMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/journal': {
      id: '/hub/journal'
      path: '/hub/journal'
      fullPath: '/hub/journal'
      preLoaderRoute: typeof HubJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/chart': {
      id: '/hub/chart'
      path: '/hub/chart'
      fullPath: '/hub/chart'
      preLoaderRoute: typeof HubChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/reset': {
      id: '/dev/reset'
      path: '/dev/reset'
      fullPath: '/dev/reset'
      preLoaderRoute: typeof DevResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/journal/history': {
      id: '/hub/journal/history'
      path: '/history'
      fullPath: '/hub/journal/history'
      preLoaderRoute: typeof HubJournalHistoryRouteImport
      parentRoute: typeof HubJournalRoute
    }
  }
}

interface HubJournalRouteChildren {
  HubJournalHistoryRoute: typeof HubJournalHistoryRoute
}

const HubJournalRouteChildren: HubJournalRouteChildren = {
  HubJournalHistoryRoute: HubJournalHistoryRoute,
}

const HubJournalRouteWithChildren = HubJournalRoute._addFileChildren(
  HubJournalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevResetRoute: DevResetRoute,
  HubChartRoute: HubChartRoute,
  HubJournalRoute: HubJournalRouteWithChildren,
  HubMentorRoute: HubMentorRoute,
  HubMindRoute: HubMindRoute,
  HubStateRoute: HubStateRoute,
  HubStrategyRoute: HubStrategyRoute,
  HubIndexRoute: HubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
