/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as HubTradesRouteImport } from './routes/hub.trades'
import { Route as HubStrategyRouteImport } from './routes/hub.strategy'
import { Route as HubStatsRouteImport } from './routes/hub.stats'
import { Route as HubStateRouteImport } from './routes/hub.state'
import { Route as HubRecoveryRouteImport } from './routes/hub.recovery'
import { Route as HubMindRouteImport } from './routes/hub.mind'
import { Route as HubMentorRouteImport } from './routes/hub.mentor'
import { Route as HubJournalRouteImport } from './routes/hub.journal'
import { Route as HubDailyRouteImport } from './routes/hub.daily'
import { Route as HubClassicRouteImport } from './routes/hub.classic'
import { Route as HubChartRouteImport } from './routes/hub.chart'
import { Route as DevResetRouteImport } from './routes/dev.reset'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as HubStrategyIndexRouteImport } from './routes/hub.strategy.index'
import { Route as HubJournalIndexRouteImport } from './routes/hub.journal.index'
import { Route as HubStrategyNewRouteImport } from './routes/hub.strategy.new'
import { Route as HubStrategyIdRouteImport } from './routes/hub.strategy.$id'
import { Route as HubJournalHistoryRouteImport } from './routes/hub.journal.history'
import { Route as HubJournalBreakdownRouteImport } from './routes/hub.journal.breakdown'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubTradesRoute = HubTradesRouteImport.update({
  id: '/hub/trades',
  path: '/hub/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const HubStrategyRoute = HubStrategyRouteImport.update({
  id: '/hub/strategy',
  path: '/hub/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const HubStatsRoute = HubStatsRouteImport.update({
  id: '/hub/stats',
  path: '/hub/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const HubStateRoute = HubStateRouteImport.update({
  id: '/hub/state',
  path: '/hub/state',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRecoveryRoute = HubRecoveryRouteImport.update({
  id: '/hub/recovery',
  path: '/hub/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMindRoute = HubMindRouteImport.update({
  id: '/hub/mind',
  path: '/hub/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMentorRoute = HubMentorRouteImport.update({
  id: '/hub/mentor',
  path: '/hub/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const HubJournalRoute = HubJournalRouteImport.update({
  id: '/hub/journal',
  path: '/hub/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HubDailyRoute = HubDailyRouteImport.update({
  id: '/hub/daily',
  path: '/hub/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const HubClassicRoute = HubClassicRouteImport.update({
  id: '/hub/classic',
  path: '/hub/classic',
  getParentRoute: () => rootRouteImport,
} as any)
const HubChartRoute = HubChartRouteImport.update({
  id: '/hub/chart',
  path: '/hub/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DevResetRoute = DevResetRouteImport.update({
  id: '/dev/reset',
  path: '/dev/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HubStrategyIndexRoute = HubStrategyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubStrategyRoute,
} as any)
const HubJournalIndexRoute = HubJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubJournalRoute,
} as any)
const HubStrategyNewRoute = HubStrategyNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HubStrategyRoute,
} as any)
const HubStrategyIdRoute = HubStrategyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HubStrategyRoute,
} as any)
const HubJournalHistoryRoute = HubJournalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HubJournalRoute,
} as any)
const HubJournalBreakdownRoute = HubJournalBreakdownRouteImport.update({
  id: '/breakdown',
  path: '/breakdown',
  getParentRoute: () => HubJournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dev/reset': typeof DevResetRoute
  '/hub/chart': typeof HubChartRoute
  '/hub/classic': typeof HubClassicRoute
  '/hub/daily': typeof HubDailyRoute
  '/hub/journal': typeof HubJournalRouteWithChildren
  '/hub/mentor': typeof HubMentorRoute
  '/hub/mind': typeof HubMindRoute
  '/hub/recovery': typeof HubRecoveryRoute
  '/hub/state': typeof HubStateRoute
  '/hub/stats': typeof HubStatsRoute
  '/hub/strategy': typeof HubStrategyRouteWithChildren
  '/hub/trades': typeof HubTradesRoute
  '/hub/': typeof HubIndexRoute
  '/hub/journal/breakdown': typeof HubJournalBreakdownRoute
  '/hub/journal/history': typeof HubJournalHistoryRoute
  '/hub/strategy/$id': typeof HubStrategyIdRoute
  '/hub/strategy/new': typeof HubStrategyNewRoute
  '/hub/journal/': typeof HubJournalIndexRoute
  '/hub/strategy/': typeof HubStrategyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dev/reset': typeof DevResetRoute
  '/hub/chart': typeof HubChartRoute
  '/hub/classic': typeof HubClassicRoute
  '/hub/daily': typeof HubDailyRoute
  '/hub/mentor': typeof HubMentorRoute
  '/hub/mind': typeof HubMindRoute
  '/hub/recovery': typeof HubRecoveryRoute
  '/hub/state': typeof HubStateRoute
  '/hub/stats': typeof HubStatsRoute
  '/hub/trades': typeof HubTradesRoute
  '/hub': typeof HubIndexRoute
  '/hub/journal/breakdown': typeof HubJournalBreakdownRoute
  '/hub/journal/history': typeof HubJournalHistoryRoute
  '/hub/strategy/$id': typeof HubStrategyIdRoute
  '/hub/strategy/new': typeof HubStrategyNewRoute
  '/hub/journal': typeof HubJournalIndexRoute
  '/hub/strategy': typeof HubStrategyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dev/reset': typeof DevResetRoute
  '/hub/chart': typeof HubChartRoute
  '/hub/classic': typeof HubClassicRoute
  '/hub/daily': typeof HubDailyRoute
  '/hub/journal': typeof HubJournalRouteWithChildren
  '/hub/mentor': typeof HubMentorRoute
  '/hub/mind': typeof HubMindRoute
  '/hub/recovery': typeof HubRecoveryRoute
  '/hub/state': typeof HubStateRoute
  '/hub/stats': typeof HubStatsRoute
  '/hub/strategy': typeof HubStrategyRouteWithChildren
  '/hub/trades': typeof HubTradesRoute
  '/hub/': typeof HubIndexRoute
  '/hub/journal/breakdown': typeof HubJournalBreakdownRoute
  '/hub/journal/history': typeof HubJournalHistoryRoute
  '/hub/strategy/$id': typeof HubStrategyIdRoute
  '/hub/strategy/new': typeof HubStrategyNewRoute
  '/hub/journal/': typeof HubJournalIndexRoute
  '/hub/strategy/': typeof HubStrategyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dev/reset'
    | '/hub/chart'
    | '/hub/classic'
    | '/hub/daily'
    | '/hub/journal'
    | '/hub/mentor'
    | '/hub/mind'
    | '/hub/recovery'
    | '/hub/state'
    | '/hub/stats'
    | '/hub/strategy'
    | '/hub/trades'
    | '/hub/'
    | '/hub/journal/breakdown'
    | '/hub/journal/history'
    | '/hub/strategy/$id'
    | '/hub/strategy/new'
    | '/hub/journal/'
    | '/hub/strategy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dev/reset'
    | '/hub/chart'
    | '/hub/classic'
    | '/hub/daily'
    | '/hub/mentor'
    | '/hub/mind'
    | '/hub/recovery'
    | '/hub/state'
    | '/hub/stats'
    | '/hub/trades'
    | '/hub'
    | '/hub/journal/breakdown'
    | '/hub/journal/history'
    | '/hub/strategy/$id'
    | '/hub/strategy/new'
    | '/hub/journal'
    | '/hub/strategy'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dev/reset'
    | '/hub/chart'
    | '/hub/classic'
    | '/hub/daily'
    | '/hub/journal'
    | '/hub/mentor'
    | '/hub/mind'
    | '/hub/recovery'
    | '/hub/state'
    | '/hub/stats'
    | '/hub/strategy'
    | '/hub/trades'
    | '/hub/'
    | '/hub/journal/breakdown'
    | '/hub/journal/history'
    | '/hub/strategy/$id'
    | '/hub/strategy/new'
    | '/hub/journal/'
    | '/hub/strategy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DevResetRoute: typeof DevResetRoute
  HubChartRoute: typeof HubChartRoute
  HubClassicRoute: typeof HubClassicRoute
  HubDailyRoute: typeof HubDailyRoute
  HubJournalRoute: typeof HubJournalRouteWithChildren
  HubMentorRoute: typeof HubMentorRoute
  HubMindRoute: typeof HubMindRoute
  HubRecoveryRoute: typeof HubRecoveryRoute
  HubStateRoute: typeof HubStateRoute
  HubStatsRoute: typeof HubStatsRoute
  HubStrategyRoute: typeof HubStrategyRouteWithChildren
  HubTradesRoute: typeof HubTradesRoute
  HubIndexRoute: typeof HubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/trades': {
      id: '/hub/trades'
      path: '/hub/trades'
      fullPath: '/hub/trades'
      preLoaderRoute: typeof HubTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/strategy': {
      id: '/hub/strategy'
      path: '/hub/strategy'
      fullPath: '/hub/strategy'
      preLoaderRoute: typeof HubStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/stats': {
      id: '/hub/stats'
      path: '/hub/stats'
      fullPath: '/hub/stats'
      preLoaderRoute: typeof HubStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/state': {
      id: '/hub/state'
      path: '/hub/state'
      fullPath: '/hub/state'
      preLoaderRoute: typeof HubStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/recovery': {
      id: '/hub/recovery'
      path: '/hub/recovery'
      fullPath: '/hub/recovery'
      preLoaderRoute: typeof HubRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/mind': {
      id: '/hub/mind'
      path: '/hub/mind'
      fullPath: '/hub/mind'
      preLoaderRoute: typeof HubMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/mentor': {
      id: '/hub/mentor'
      path: '/hub/mentor'
      fullPath: '/hub/mentor'
      preLoaderRoute: typeof HubMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/journal': {
      id: '/hub/journal'
      path: '/hub/journal'
      fullPath: '/hub/journal'
      preLoaderRoute: typeof HubJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/daily': {
      id: '/hub/daily'
      path: '/hub/daily'
      fullPath: '/hub/daily'
      preLoaderRoute: typeof HubDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/classic': {
      id: '/hub/classic'
      path: '/hub/classic'
      fullPath: '/hub/classic'
      preLoaderRoute: typeof HubClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/chart': {
      id: '/hub/chart'
      path: '/hub/chart'
      fullPath: '/hub/chart'
      preLoaderRoute: typeof HubChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/reset': {
      id: '/dev/reset'
      path: '/dev/reset'
      fullPath: '/dev/reset'
      preLoaderRoute: typeof DevResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/strategy/': {
      id: '/hub/strategy/'
      path: '/'
      fullPath: '/hub/strategy/'
      preLoaderRoute: typeof HubStrategyIndexRouteImport
      parentRoute: typeof HubStrategyRoute
    }
    '/hub/journal/': {
      id: '/hub/journal/'
      path: '/'
      fullPath: '/hub/journal/'
      preLoaderRoute: typeof HubJournalIndexRouteImport
      parentRoute: typeof HubJournalRoute
    }
    '/hub/strategy/new': {
      id: '/hub/strategy/new'
      path: '/new'
      fullPath: '/hub/strategy/new'
      preLoaderRoute: typeof HubStrategyNewRouteImport
      parentRoute: typeof HubStrategyRoute
    }
    '/hub/strategy/$id': {
      id: '/hub/strategy/$id'
      path: '/$id'
      fullPath: '/hub/strategy/$id'
      preLoaderRoute: typeof HubStrategyIdRouteImport
      parentRoute: typeof HubStrategyRoute
    }
    '/hub/journal/history': {
      id: '/hub/journal/history'
      path: '/history'
      fullPath: '/hub/journal/history'
      preLoaderRoute: typeof HubJournalHistoryRouteImport
      parentRoute: typeof HubJournalRoute
    }
    '/hub/journal/breakdown': {
      id: '/hub/journal/breakdown'
      path: '/breakdown'
      fullPath: '/hub/journal/breakdown'
      preLoaderRoute: typeof HubJournalBreakdownRouteImport
      parentRoute: typeof HubJournalRoute
    }
  }
}

interface HubJournalRouteChildren {
  HubJournalBreakdownRoute: typeof HubJournalBreakdownRoute
  HubJournalHistoryRoute: typeof HubJournalHistoryRoute
  HubJournalIndexRoute: typeof HubJournalIndexRoute
}

const HubJournalRouteChildren: HubJournalRouteChildren = {
  HubJournalBreakdownRoute: HubJournalBreakdownRoute,
  HubJournalHistoryRoute: HubJournalHistoryRoute,
  HubJournalIndexRoute: HubJournalIndexRoute,
}

const HubJournalRouteWithChildren = HubJournalRoute._addFileChildren(
  HubJournalRouteChildren,
)

interface HubStrategyRouteChildren {
  HubStrategyIdRoute: typeof HubStrategyIdRoute
  HubStrategyNewRoute: typeof HubStrategyNewRoute
  HubStrategyIndexRoute: typeof HubStrategyIndexRoute
}

const HubStrategyRouteChildren: HubStrategyRouteChildren = {
  HubStrategyIdRoute: HubStrategyIdRoute,
  HubStrategyNewRoute: HubStrategyNewRoute,
  HubStrategyIndexRoute: HubStrategyIndexRoute,
}

const HubStrategyRouteWithChildren = HubStrategyRoute._addFileChildren(
  HubStrategyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DevResetRoute: DevResetRoute,
  HubChartRoute: HubChartRoute,
  HubClassicRoute: HubClassicRoute,
  HubDailyRoute: HubDailyRoute,
  HubJournalRoute: HubJournalRouteWithChildren,
  HubMentorRoute: HubMentorRoute,
  HubMindRoute: HubMindRoute,
  HubRecoveryRoute: HubRecoveryRoute,
  HubStateRoute: HubStateRoute,
  HubStatsRoute: HubStatsRoute,
  HubStrategyRoute: HubStrategyRouteWithChildren,
  HubTradesRoute: HubTradesRoute,
  HubIndexRoute: HubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
